### ISSUE TITLE
"This run is in progress." after simulation ends?

### ISSUE THREAD

**Issue by chaumanfung** [LucasJavaudin/MetropolisWebInterface#12]
Hello,

Mon May 20 18:12:07 2019:Ending simulation normally
Mon May 20 18:12:07 2019:Elapsed:0D2H21M40S
Mon May 20 18:12:07 2019:Performance:0D0H7M5S per iteration
(at https://metropolis.sauder.ubc.ca/182/run/916)
However, now the run is still in progress. This seems to take unusually long (more than an hour to "end" after the iterations are over? 

Thanks in advance!

**Comment by LucasJavaudin** [comment]
It is happening again. :/

I manually ran the ending script but there is no error message in the logs to let me know what happened.

**Comment by LucasJavaudin** [comment]
My fix is no longer in the code since commit c6de5706b973bb88563c9e091bbe169dc9ddbea5.
An idea what happened @syrix78?

**Comment by syrix78** [comment]
My guess is that since I forked the master branch before @LucasJavaudin implemented the fix, I probably forgot to pull changes before merging my branch (and as a consequence never took into account the fixe). Pretty weird as I did do a pull before merge.
I'll try manually adding all the commits to my code and push it back.

**Comment by syrix78** [comment]
As I suspected, this was the case. I manually applied every commit since May 2nd. It should work now

**Comment by chaumanfung** [comment]
Looks like it... This link result file I get from this run was the old version, where I only get the in-flows (without out-flows etc.)...
Glad that it's fixed now!
