### ISSUE TITLE
links Issue

### ISSUE THREAD

**Issue by FilippoAmadio** [LucasJavaudin/MetropolisWebInterface#3]
Hello, I am not sure to have perfectly understood how to import links. The headers should be ok, I replicated the same headers appearing if I click on export link. However when I try to impor them it says there's something wrong with the headers. My concerns are about three variables: origin, destination and congestion function. Regarding Origin and Destination, should I set the variables values with the id of the 2 (or more) zones I am considering? ( If a want to compute the shortest path from zone id=1 to zone id=2 I put origin=1 and destination=2, is this work like this?). The second concern is related to Congestion Function, is it enough to set, as a value, the id of the congestion function I want? 
Thanks in advance.

I attached the three file concerning zones intersections and links
[metropolis_interesction.txt](https://github.com/LucasJavaudin/MetropolisWebInterface/files/3063222/metropolis_interesction.txt)
[metropolis_link.txt](https://github.com/LucasJavaudin/MetropolisWebInterface/files/3063223/metropolis_link.txt)
[metropolis_zone.txt](https://github.com/LucasJavaudin/MetropolisWebInterface/files/3063224/metropolis_zone.txt)

**Comment by LucasJavaudin** [comment]
- The value of the variable _origin_ and _destination_ must be the id of a zone or an intersection already existing in the simulation. Your file `metropolis_link.txt` is correct in this regard.
- You are correct, the value of the variable _function_ must be the id of the congestion function of the link.
- You cannot import the file `metropolis_link.txt` because the column _capacity_ is empty for some rows. Also, the values of _origin_ and _destination_ are always the same so you will need to change same to create your network a proper network.
